CREATE TABLE "CASHBACK"."DGT001_PNO_CSB"  ( 
	"PNOCSB_COD"                	VARCHAR2(36 BYTE) NOT NULL,
	"PNOCSB_DAT_INC"            	DATE NOT NULL,
	"PNOCSB_NOM_PNO"            	VARCHAR2(50 BYTE) NOT NULL,
	"PNOCSB_PEC_CSB_CCO"        	NUMBER(5,2) NOT NULL,
	"PNOCSB_PEC_CSB_CCR"        	NUMBER(5,2) NOT NULL,
	"PNOCSB_PEC_CSB_CCO_NVO_BIN"	NUMBER NULL,
	"PNOCSB_PEC_CSB_CCR_NVO_BIN"	NUMBER NULL,
	CONSTRAINT "PK_DGP001_PRM_CSB" PRIMARY KEY("PNOCSB_COD")
	NOT DEFERRABLE VALIDATE 
);

CREATE TABLE "CASHBACK"."DGT001_PNO_CSB_OLD"  ( 
	"PNOCSB_COD"                	VARCHAR2(36 BYTE) NOT NULL,
	"PNOCSB_DAT_INC"            	DATE NOT NULL,
	"PNOCSB_NOM_PNO"            	VARCHAR2(50 BYTE) NOT NULL,
	"PNOCSB_PEC_CSB_CCO"        	NUMBER(5,2) NOT NULL,
	"PNOCSB_PEC_CSB_CCR"        	NUMBER(5,2) NOT NULL,
	"PNOCSB_PEC_CSB_CCO_NVO_BIN"	NUMBER NULL,
	"PNOCSB_PEC_CSB_CCR_NVO_BIN"	NUMBER NULL 
);

CREATE TABLE "CASHBACK"."DGT002_RLC_PNO_CSB"  ( 
	"PNOCSB_COD" 	VARCHAR2(36 BYTE) NOT NULL,
	"COD_PNO_BEN"	NUMBER(6) NOT NULL 
);

CREATE TABLE "CASHBACK"."DGT003_CSB_CCO"  ( 
	"CSBCCO_COD"    	VARCHAR2(36 BYTE) NOT NULL,
	"CSBCCO_TIP"    	NUMBER(4) NOT NULL,
	"CSBCCO_COD_TRS"	VARCHAR2(36 BYTE) NULL,
	"CSBCCO_DSC_TRS"	VARCHAR2(150 BYTE) NULL,
	"CSBCCO_DAT_INC"	DATE NOT NULL,
	"CSBCCO_CPF"    	VARCHAR2(15 BYTE) NOT NULL,
	"CSBCCO_AGE"    	NUMBER(4) NOT NULL,
	"CSBCCO_NRO_CTA"	NUMBER(8) NOT NULL,
	"CSBCCO_VLR_TRS"	NUMBER(10,2) NOT NULL,
	"CSBCCO_VLR_CSB"	NUMBER(10,6) NOT NULL,
	"CSBCCO_PEC_CSB"	NUMBER(5,2) NOT NULL,
	"CSBCCO_DAT_CLC"	DATE NULL,
	"CSBCCO_DAT_PAG"	DATE NULL,
	"CSBCCO_STS"    	NUMBER(3) NOT NULL,
	CONSTRAINT "PK_DGT003_CSB_CCO" PRIMARY KEY("CSBCCO_COD")
	NOT DEFERRABLE VALIDATE 
);

CREATE TABLE "CASHBACK"."DGT004_CSB_CCR"  ( 
	"CSBCCR_COD"    	VARCHAR2(36 BYTE) NOT NULL,
	"CSBCCR_TIP"    	NUMBER(4) NOT NULL,
	"CSBCCR_COD_TRS"	VARCHAR2(150 BYTE) NULL,
	"CSBCCR_DSC_TRS"	VARCHAR2(150 BYTE) NULL,
	"CSBCCR_DAT_INC"	DATE NOT NULL,
	"CSBCCR_CPF"    	VARCHAR2(15 BYTE) NOT NULL,
	"CSBCCR_COD_CTA"	NUMBER(12) NOT NULL,
	"CSBCCR_VLR_TRS"	NUMBER(10,2) NOT NULL,
	"CSBCCR_VLR_CSB"	NUMBER(10,6) NOT NULL,
	"CSBCCR_PEC_CSB"	NUMBER(5,2) NOT NULL,
	"CSBCCR_DAT_CLC"	DATE NULL,
	"CSBCCR_DAT_PAG"	DATE NULL,
	"CSBCCR_STS"    	NUMBER(3) NOT NULL,
	CONSTRAINT "PK_DGT004_CSB_CCR" PRIMARY KEY("CSBCCR_COD")
	NOT DEFERRABLE VALIDATE 
);

CREATE TABLE "CASHBACK"."DGT005_CSB_PRM_STS"  ( 
	"PRMSTS_COD"                	NUMBER(15,5) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20 NOCYCLE ORDER) NOT NULL,
	"PRMSTS_COD_STS_CSB"        	NUMBER(15,5) NOT NULL,
	"PRMSTS_DSC_STS_CSB_DFT"    	VARCHAR2(30 BYTE) NOT NULL,
	"PRMSTS_DSC_STS_CSB_AMG_CCR"	VARCHAR2(30 BYTE) NULL,
	"PRMSTS_DSC_STS_CSB_AMG_CCO"	VARCHAR2(30 BYTE) NULL,
	"PRMSTS_STS_DFT_USA"        	NUMBER(15,5) NOT NULL,
	"PRMSTS_STS_OBS"            	VARCHAR2(300 BYTE) NULL,
	"PRMSTS_DAT_INC"            	DATE NOT NULL,
	"PRMSTS_DAT_ATU"            	DATE NOT NULL 
);