version: '3'
services:
  # toggles-db:
  #   image: postgres:alpine
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASS}
  #   ports:
  #     - ${POSTGRES_PORT}:${POSTGRES_PORT}
  #   container_name: toggles-db
  #   volumes: 
  #     - ./scripts/pg-init.sql:/docker-entrypoint-initdb.d/pg-init.sql
  #   networks:
  #     - skynet
  oracle-db:
    image: docker.pkg.github.com/gm50x/envs/oracledb:latest
    environment:
      ORACLE_PWD: ${ORACLE_PWD}
    ports:
      - ${ORACLE_PORT}:1521
    shm_size: 2gb
    container_name: oracle-db
    volumes:
      - ./scripts/ora-init.sql:/docker-entrypoint-initdb.d/startup/ora-init.sql
    networks:
      - skynet
networks:
  skynet:
      driver: bridge