--- RUN AFTER CONTAINER INIT WITH:

--- CASHBACK USER
CREATE USER CASHBACK IDENTIFIED BY pwd4cashback;
GRANT CONNECT, RESOURCE, DBA TO CASHBACK;
GRANT CREATE SESSION TO CASHBACK;
GRANT ALL PRIVILEGES TO CASHBACK;
GRANT UNLIMITED TABLESPACE TO CASHBACK;

--- CASHBACK TABLE DATA
CREATE TABLE CASHBACK.EXTRATO (
	ID_EXTRATO NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1) NOT NULL,
	DESCRICAO NVARCHAR2(100) NOT NULL,
	PRIMARY KEY(ID_EXTRATO)
);

INSERT INTO CASHBACK.EXTRATO (DESCRICAO) VALUES ('Amazon');
INSERT INTO CASHBACK.EXTRATO (DESCRICAO) VALUES ('Fasthop');
INSERT INTO CASHBACK.EXTRATO (DESCRICAO) VALUES ('Submarino');
